improve error handling

diff --git a/src/commands/record_deployment.yml b/src/commands/record_deployment.yml
--- a/src/commands/record_deployment.yml
+++ b/src/commands/record_deployment.yml
@@ -21,6 +21,15 @@ steps:
   - run:
       name: Check application ID
       command: |
+        if [ -n "<< parameters.api-key >>" ]; then
+          NEW_RELIC_API_KEY="<< parameters.api-key >>"
+        fi
+
+        if [ -z "$NEW_RELIC_API_KEY" ]; then 
+          "Oops, either api-key or NEW_RELIC_API_KEY was not provided. We can't go any further without one of these."
+          exit 1
+        fi
+
         if test -z "<< parameters.app-id >>" -a -n "<< parameters.app-name >>" ; then
           echo "'app-id' not provided. Trying to figure it out from 'app-name'..."
           APP_NAME="<< parameters.app-name >>"
@@ -31,12 +40,14 @@ steps:
           echo "'app-name' not provided. Trying to figure it out from 'app-id'..."
           APP_ID="<< parameters.app-id >>"
           APP_NAME=$(curl -sX GET "https://api.newrelic.com/v2/applications.json" -H "X-Api-Key:$NEW_RELIC_API_KEY" |  jq -r ".applications[] | select(.id == "$APP_ID") | .name")
+          [ -z "$APP_ID" ] && echo "Sorry, App ID not found for app '$APP_NAME'." && exit 1;
           echo "Found app-name: '$APP_NAME' for app-id: '$APP_ID'"
         elif test -z "<< parameters.app-name >>" -a -z "<< parameters.app-id >>" ; then
           echo "Oops, either app-id or app-name was not provided. We can't go any further without one of these."
           exit 1
         fi
 
+        echo 'export NEW_RELIC_API_KEY="'"$NEW_RELIC_API_KEY"'"' >> $BASH_ENV
         echo 'export APP_NAME="'"$APP_NAME"'"' >> $BASH_ENV
         echo 'export APP_ID="'"$APP_ID"'"' >> $BASH_ENV
 
@@ -55,8 +66,6 @@ steps:
   - run:
       name: Record deployment
       command: |
-        echo "[DEBUG] BASH_ENV: $BASH_ENV"
-        set -x
         echo "Recording deployment on New Relic for: APP_ID: $APP_ID / APP_NAME: $APP_NAME"
         if [ -n "$APP_ID" ]; then
           response=$(curl -s -w "\n%{http_code}" -X POST "https://api.newrelic.com/v2/applications/${APP_ID}/deployments.json" \
@@ -72,12 +81,9 @@ steps:
             }
           }')
 
-          response=(${response[@]}) # convert to array
-          code=${response[-1]} # get last element (last line)
-          body=${response[@]::${#response[@]}-1} # get all elements except last
-
-          echo "$body"
-          if [ $code -gt 201 ]; then
+          code=$(echo $response | tail -n1)
+          if [[ "$code" -gt 201 ]]; then
+            echo $response
             exit $code
           fi
         else
