fix shell syntax

diff --git a/src/commands/record_deployment.yml b/src/commands/record_deployment.yml
--- a/src/commands/record_deployment.yml
+++ b/src/commands/record_deployment.yml
@@ -24,14 +24,14 @@ steps:
         if test -z "<< parameters.app-id >>" -a -n "<< parameters.app-name >>" ; then
           echo "'app-id' not provided. Trying to figure it out from 'app-name'..."
           APP_NAME="<< parameters.app-name >>"
-          APP_ID=$(curl -sX GET "https://api.newrelic.com/v2/applications.json" -H "X-Api-Key:${NEW_RELIC_API_KEY}" |  jq -r ".applications[] | select(.name == \"${APP_NAME}\") | .id")
-          if [ -z "{$APP_ID}" ] && echo "Sorry, App ID not found for app '${APP_NAME}'." && exit 1;
-          echo "Found app-id: '${APP_ID}' for app-name: '${APP_NAME}'"
+          APP_ID=$(curl -sX GET "https://api.newrelic.com/v2/applications.json" -H "X-Api-Key:$NEW_RELIC_API_KEY" |  jq -r ".applications[] | select(.name == \"$APP_NAME\") | .id")
+          if [ -z "$APP_ID" ] && echo "Sorry, App ID not found for app '$APP_NAME'." && exit 1;
+          echo "Found app-id: '$APP_ID' for app-name: '$APP_NAME'"
         elif test -z "<< parameters.app-name >>" -a -n "<< parameters.app-id >>" ; then
           echo "'app-name' not provided. Trying to figure it out from 'app-id'..."
           APP_ID="<< parameters.app-id >>"
-          APP_NAME=$(curl -sX GET "https://api.newrelic.com/v2/applications.json" -H "X-Api-Key:${NEW_RELIC_API_KEY}" |  jq -r ".applications[] | select(.id == "${APP_ID}") | .name")
-          echo "Found app-name: '${APP_NAME}' for app-id: '${APP_ID}'"
+          APP_NAME=$(curl -sX GET "https://api.newrelic.com/v2/applications.json" -H "X-Api-Key:$NEW_RELIC_API_KEY" |  jq -r ".applications[] | select(.id == "$APP_ID") | .name")
+          echo "Found app-name: '$APP_NAME' for app-id: '$APP_ID'"
         elif test -z "<< parameters.app-name >>" -a -z "<< parameters.app-id >>" ; then
           echo "Oops, either app-id or app-name was not provided. We can't go any further without one of these."
           exit 1
